#+TITLE: Instrucciones generales para hacer la memoria del TFG

Este documento contiene guías e ideas generales (no reglas) para estructurar el trabajo de fin de grado.

* Normativa TFG

Lo primero es leerse la normativa del TFG del año que nos toca. Siempre hay información relevante.

* Capítulos

Hay 5 partes importantes que todo trabajo académico tiene que contemplar. Lo normal es estructurar el documento de forma que estas partes se correspondan con los capítulos:

** Resumen (abstract)

Unos pocos párrafos que sirvan para que alguien no tenga ni idea de lo que se está leyendo sepa: /cuál es el problema que se quiere resolver/, /cómo se ha resuelto/ y /cuáles han sido los resultados más importantes/.

** Introducción

Es útil empezar a escribir contando de forma general el estado de la ciencia o la técnica en un punto dado, e introduciendo el problema general por el que se trabaja.

*** Motivación

La motivación es la razón *técnica* por la que se lleva a cabo un desarrollo. La motivación describe por qué se hace el trabajo (por ejemplo, se quiere mejorar la identificación automática de personas por la imagen de su cara) y por qué se intenta, en particular, la solución que se propone.

*** Hipótesis de partida

La hipótesis de partida son las ideas que aún no sabemos si son ciertas, pero vamos a trabajar para demostrarlas. Por ejemplo, que usando números primos la identificación de caras será más efectiva.

*** Objetivos

Una lista /concreta/ de cosas que se quieren conseguir. Muchas veces ayudará hacerlo como una lista con topos:

- Descubrir los números primos que acaben en 7
- Implementar un algoritmo que descubra las caras que se parecen a 7
- Hacer un experimento con caras reales

*** Metodología y plan de trabajo

Un plan, a priori, de cómo se van a repartir los recursos y el tiempo, por tareas. Algo parecido a un [[https://es.wikipedia.org/wiki/Diagrama_de_Gantt][diagrama de Gantt]], aunque no tiene que ser tan técnico.

*** Estructura del resto del documento

Esto es más una costumbre, pero ayuda. Algo del estilo de: "En el capítulo 2 se estudiará el estado del arte. En el 3, 4 y 5 se describe la propuesta basada en números primos..."

** Estudio del trabajo previo (o "estado del arte")
Una parte lenta de hacer, pero muy importante. En esta parte se describe todo el trabajo sobre el que se construye nuestra propuesta. Tiene que tener muchas citas, y esas citas son /idealmente/ artículos y libros técnicos y científicos. Sólo en el caso de citar algo que no esté como publicación clásica (un videojuego) se permite no ser tan riguroso.

*** Trabajos parecidos o relacionados
Aquí hay que hacer una revisión general de todo lo que se parezca a nuestro trabajo. *** Tecnologías usadas en el trabajo
Aquí se describen las tecnologías que usamos: librerías, entornos, plataformas... No hay que poner imágenes con los logos ni contar cosas triviales (no hay que explicar qué navegador de Internet usamos, a no ser que el proyecto vaya de eso). ** Contribución

Esta parte puede ser un solo capítulo, aunque pueden (y suelen) ser más, dependiendo de lo que se cuente. Es donde se explica lo que se ha hecho, la arquitectura, pruebas, experimentos, resultados... Idealmente, primero lo general y finalmente los resultados. ** Discusión

Es un capítulo que /discute/, desde el punto de vista técnico, las ventajas y limitaciones de nuestro trabajo. No hay inconveniente por admitir explícitamente las limitaciones, sobre todo si esas limitaciones no las ha superado nadie. No hay que dejarse nada, todo lo que no se discuta será discutido por el tribunal, y eso suele ser peor. ** Conclusiones y trabajo futuro

El capítulo final es bastante esquemático. Se empieza con algo parecido al /abstract/, pero centrándose más en los resultados. Puede parecer redundante, porque lo es, pero se espera que se cuente aquí. Después se habla de lo que se podría hacer a partir de aquí, basándose en los resultados o en el producto de la implementación. * Ideas generales


- Todas las imágenes y figuras tienen que ser útiles (nada de logos)
- Todas las imágenes, figuras, tablas y demás tienen que estar numeradas con esquema (Tabla 2.5), y tener un pie que describa perfectamente lo que se ve. - Los títulos de capítulos y secciones tienen que ser descriptivos, no atractivos (aunque si se consiguen ambas cosas, mejor). - No se escribe en "personal". No se ponen nada como "hemos aprendido mucho", es un documento técnico. Para referirse a uno mismo, las fórmulas clásicas son usar la primera persona del plural ("hemos llevado a cabo"), o el impersonal ("se ha llevado a cabo"). - Dentro de lo razonable, repetir cosas en varios sitios no es necesariamente malo. Es muy raro que alguien se lea un documento técnico como se lee una novela, se va por secciones, se cambia de capítulo... Aunque no hay que exagerar esto, hay que asumir que mucha gente se leerá las conclusiones casi lo primero.
* Comunicación

En última instancia, una memoria técnica es un ejercicio de comunicación. Se escribe para que alguien, en 1 hora, sepa todo lo relevante que ha ocurrido durante todo un año de trabajo. Filtrar, condensar, explicar bien las causas y las decisiones, y estructurar de forma que el lector tenga que emplear poco esfuerzo para entender, es fundamental. * Fechas

Empezad a escribir cuanto antes. Cuesta mucho esfuerzo, y en general se tiene poca práctica. Lo ideal es mandar muchas versiones al principio para que, muy pronto, la estructura coja forma y se corrijan, cuanto antes, los defectos básicos.
